// 2025-03-30-angular/02-social-network-client/src/app/components/layout/layout/layout.component.ts
import { Component } from '@angular/core';
import { HeaderComponent } from "../header/header.component";
import { FooterComponent } from "../footer/footer.component";
import { FollowingComponent } from "../../follows/following/following.component";
import { FollowersComponent } from "../../follows/followers/followers.component";
import { ProfileComponent } from "../../posts/profile/profile.component";

@Component({
  selector: 'app-layout',
  imports: [HeaderComponent, FooterComponent, FollowingComponent, FollowersComponent, ProfileComponent],
  templateUrl: './layout.component.html',
  styleUrl: './layout.component.css'
})
export class LayoutComponent {

}

<div id="grid">
    <header>
        <app-header></app-header>
    </header>
    <aside>
        <app-following></app-following>
    </aside>
    <aside>
        <app-followers></app-followers>
    </aside>
    <main>
        <app-profile></app-profile>
    </main>
    <footer>
        <app-footer></app-footer>
    </footer>
</div>

// 2025-01-07/social-network-client/src/components/layout/layout/Layout.tsx
import Feed from '../../posts/feed/Feed'
import Profile from '../../posts/profile/Profile'
import Followers from '../followers/Followers'
import Following from '../following/Following'
import Footer from '../footer/Footer'
import Header from '../header/Header'
import Routing from '../routing/Routing'
import './Layout.css'

export default function Layout() {
    return (
        <div className='Layout'>
            <header>
                <Header />                
            </header>                
            <aside>
                <Following />
            </aside>
            <aside>
                <Followers />
            </aside>
            <main>
                <Routing />
            </main>
            <footer>
                <Footer />
            </footer>
        </div>
    )
}
