// 2025-04-01-angular/test-example/front/src/app/components/posts/post/post.component.ts
import { Component, input, output } from '@angular/core';
import { Post } from '../../../models/post/post.model';
import { ProfileService } from '../../../services/profile.service';
import { CommentsComponent } from "../comments/comments.component";
import { Router } from '@angular/router';

@Component({
  selector: 'app-post',
  imports: [CommentsComponent],
  templateUrl: './post.component.html',
  styleUrl: './post.component.css'
})
export class PostComponent {

    constructor (
        public profileService: ProfileService,
        public router: Router
    ) {

    }

    post = input<Post>()
    deletedPost = output<string>()
    deletedComment = output<{postId: string, commentId: string}>()

    async deleteMe() {
        try {
            await this.profileService.deletePost(this.post()!.id)
            this.deletedPost.emit(this.post()!.id)
        } catch (e) {
            alert(e)
        }
    }

    async editMe() {
        this.router.navigate([`/edit/${this.post()!.id}`])
    }

    deleteComment(id: string) {
        this.deletedComment.emit({postId: this.post()!.id, commentId: id})
    }

}

<div id="post">
    <h3>{{post()?.title}}</h3>
    <p>by {{post()?.user?.name}} at {{post()?.createdAt}}</p>
    <div>{{post()?.body}}</div>
    <button (click)="deleteMe()">delete</button>
    <button (click)="editMe()">edit</button>
    <app-comments
        [comments]="post()?.comments"
        [postId]="post()?.id"
        (deletedComment)="deleteComment($event)"
    >

    </app-comments>
</div>

// 2025-02-25/02-social-network-integration/frontend/src/components/posts/post/Post.tsx
import './Post.css'
import PostModel from '../../../models/post/Post'
import ProfileService from '../../../services/auth-aware/Profile'
import { useNavigate } from 'react-router-dom'
import Comments from '../comments/Comments'
import { useAppDispatch } from '../../../redux/hooks'
import { remove } from '../../../redux/profileSlice'
import useService from '../../../hooks/useService'

interface PostProps {
    post: PostModel,
    isAllowActions?: boolean, // === isAllowActions: boolean | undefined
}
export default function Post(props: PostProps): JSX.Element {

    const {
        title,
        body,
        createdAt,
        id,
        comments
    } = props.post
    const { name } = props.post.user


    const navigate = useNavigate()

    const dispatch = useAppDispatch()

    const profileService = useService(ProfileService)

    async function deleteMe() {
        if (confirm(`are you sure you want to delete "${title}"`)) {
            try {
                await profileService.remove(id)
                dispatch(remove({ id }))
            } catch (e) {
                alert(e)
            }
        }
    }

    function editMe() {
        navigate(`/edit/${id}`)
    }

    return (
        <div className='Post'>
            <div>
                {title}
            </div>
            <div>
                by {name} at {createdAt}
            </div>
            <div>
                {body}
            </div>
            {props.isAllowActions &&
                <div>
                    <button onClick={editMe}>Edit</button>
                    <button onClick={deleteMe}>Delete</button>
                </div>
            }
            <Comments
                comments={comments}
                postId={id}
            />
        </div>
    )
}
