// 2025-01-12/social-network-client/src/components/posts/post/Post.tsx
import './Post.css'
import PostModel from '../../../models/post/Post'
import profileService from '../../../services/profile'

interface PostProps {
    post: PostModel
}
export default function Post(props: PostProps): JSX.Element {

    const { title, body, createdAt, id } = props.post
    const { name } = props.post.user
    
    async function deleteMe() {

        try {
            await profileService.remove(id)
        } catch (e) {
            alert(e)
        }
    }

    return (
        <div className='Post'>
            <div>
                {title}
            </div>
            <div>
                by {name} at {createdAt}
            </div>
            <div>
                {body}
            </div>
            <div>
                <button onClick={deleteMe}>Delete</button>
            </div>
        </div>
    )
}

// 2025-04-01-angular/02-social-network-client/src/app/components/posts/post/post.component.ts
import { Component, input, output } from '@angular/core';
import { Post } from '../../../models/post/post.model';
import { ProfileService } from '../../../services/profile.service';
import { CommentsComponent } from "../comments/comments.component";

@Component({
  selector: 'app-post',
  imports: [CommentsComponent],
  templateUrl: './post.component.html',
  styleUrl: './post.component.css'
})
export class PostComponent {

    constructor (
        public profileService: ProfileService
    ) {

    }

    post = input<Post>()
    deletedPost = output<string>()

    async deleteMe() {
        try {
            await this.profileService.deletePost(this.post()!.id)
            this.deletedPost.emit(this.post()!.id)
        } catch (e) {
            alert(e)
        }
    }

}

<div id="post">
    <h3>{{post()?.title}}</h3>
    <p>by {{post()?.user?.name}} at {{post()?.createdAt}}</p>
    <div>{{post()?.body}}</div>
    <button (click)="deleteMe()">delete</button>
    <app-comments
        [comments]="post()?.comments"
    >

    </app-comments>
</div>
